### PR TITLE
fix race between proxy.Serve and Close

### LINKED ISSUE #286: flaky data racy in proxy during Close
I saw this on one of our Travis runs:

```
WARNING: DATA RACE
Read at 0x00c000097a08 by goroutine 30:
  internal/race.Read()
      /Users/travis/.gimme/versions/go1.11.6.darwin.amd64/src/internal/race/race.go:37 +0x38
  sync.(*WaitGroup).Add()
      /Users/travis/.gimme/versions/go1.11.6.darwin.amd64/src/sync/waitgroup.go:71 +0x16b
  github.com/google/martian.(*Proxy).handleLoop()
      /Users/travis/gopath/pkg/mod/github.com/google/martian@v2.1.0+incompatible/proxy.go:221 +0x7f
Previous write at 0x00c000097a08 by goroutine 77:
  internal/race.Write()
      /Users/travis/.gimme/versions/go1.11.6.darwin.amd64/src/internal/race/race.go:41 +0x38
  sync.(*WaitGroup).Wait()
      /Users/travis/.gimme/versions/go1.11.6.darwin.amd64/src/sync/waitgroup.go:128 +0xef
  github.com/google/martian.(*Proxy).Close()
      /Users/travis/gopath/pkg/mod/github.com/google/martian@v2.1.0+incompatible/proxy.go:145 +0xcc
  cloud.google.com/go/httpreplay/internal/proxy.(*Proxy).Close()
      /Users/travis/gopath/pkg/mod/cloud.google.com/go@v0.37.0/httpreplay/internal/proxy/record.go:200 +0x54
  cloud.google.com/go/httpreplay.(*Replayer).Close()
      /Users/travis/gopath/pkg/mod/cloud.google.com/go@v0.37.0/httpreplay/httpreplay.go:152 +0x4b
  gocloud.dev/internal/testing/setup.NewAWSSession2.func2()
      /Users/travis/gopath/src/gocloud.dev/internal/testing/setup/setup.go:139 +0x41
  gocloud.dev/pubsub/awssnssqs.(*harness).Close()
      /Users/travis/gopath/src/gocloud.dev/pubsub/awssnssqs/awssnssqs_test.go:195 +0x4c
  gocloud.dev/pubsub/drivertest.testMetadata()
      /Users/travis/gopath/src/gocloud.dev/pubsub/drivertest/drivertest.go:714 +0x901
  gocloud.dev/pubsub/drivertest.RunConformanceTests.func1()
      /Users/travis/gopath/src/gocloud.dev/pubsub/drivertest/drivertest.go:167 +0x6f
  testing.tRunner()
      /Users/travis/.gimme/versions/go1.11.6.darwin.amd64/src/testing/testing.go:827 +0x162
Goroutine 30 (running) created at:
  github.com/google/martian.(*Proxy).Serve()
      /Users/travis/gopath/pkg/mod/github.com/google/martian@v2.1.0+incompatible/proxy.go:216 +0x392
Goroutine 77 (finished) created at:
  testing.(*T).Run()
      /Users/travis/.gimme/versions/go1.11.6.darwin.amd64/src/testing/testing.go:878 +0x659
  gocloud.dev/pubsub/drivertest.RunConformanceTests()
      /Users/travis/gopath/src/gocloud.dev/pubsub/drivertest/drivertest.go:167 +0x5c3
  gocloud.dev/pubsub/awssnssqs.TestConformance()
      /Users/travis/gopath/src/gocloud.dev/pubsub/awssnssqs/awssnssqs_test.go:212 +0xa5
  testing.tRunner()
      /Users/travis/.gimme/versions/go1.11.6.darwin.amd64/src/testing/testing.go:827 +0x162
==================
```

### PR DESCRIPTION
**Pull request by vangent**
Fixes #286.

It's not OK to call `Add` and `Wait` concurrently on a `sync.WaitGroup`. `Done` is OK to call whenever:
https://golang.org/pkg/sync/#WaitGroup.Add

Normally the fix would be to move the call to `Add` out of the goroutine (e.g., from inside `handleLoop` to `Serve` before `go handleLoop`). However, it appears that `Serve` itself is often called in a user goroutine, so that won't help here.

The test fails on `go test -count=1 -race --run TestRacyClose` without the fix.

### CODE REVIEW

File: proxy.go [hunk 1]
```diff
@@ -218,9 +220,14 @@ func (p *Proxy) Serve(l net.Listener) error {
 }
 
 func (p *Proxy) handleLoop(conn net.Conn) {
+	p.connsMu.Lock()
 	p.conns.Add(1)
+	p.connsMu.Unlock()
 	defer p.conns.Done()
 	defer conn.Close()
+	if p.Closing() {
```
Comment (vangent) [inline proxy.go]: This is technically an independent change, but seems like a good idea. I can remove it if you prefer.

File: proxy.go [hunk 2]
```diff
@@ -142,7 +142,9 @@ func (p *Proxy) Close() {
 	close(p.closing)
 
 	log.Infof("martian: waiting for connections to close")
```
Comment (vangent) [inline proxy.go]: Ideally, wouldn't `Close` wait until all of the outstanding calls to `Serve` have returned? IIUC, since `Listener.Accept` is blocking, the best way to do that would be to keep a slice of `net.Listener`s being used by `Serve`, and close them all during `Close`. And maybe another `sync.WaitGroup` to keep track of the `Serve` calls. Let me know if you think this is a good change, it's independent from this PR.

**Comment by vangent** [comment]
I don't think the test failure is related to this change, but please confirm.
